CREATE TABLE RUN_LOG (
ID INT NOT NULL AUTO_INCREMENT,
SCRIPT TEXT,
ANCHOR_CITY_ID INT,
RUN_TIME DATETIME,
RECORDS_INSERTED INT,
RECORDS_SKIPPED INT,
PRIMARY KEY(ID)
);

CREATE TABLE EVENTS (
EVENT_ID INT NOT NULL AUTO_INCREMENT,
EVENT_NAME TEXT,
PRIMARY KEY(EVENT_ID)
);

ALTER TABLE EVENTS AUTO_INCREMENT = 3000;

CREATE TABLE CAT_NAME (
NAME_ID INT NOT NULL AUTO_INCREMENT,
NAME_TEXT TEXT,
PRIMARY KEY (NAME_ID)
);

ALTER TABLE CAT_NAME AUTO_INCREMENT = 7000;

CREATE TABLE CATEGORY(
CATEGORY_ID INT NOT NULL AUTO_INCREMENT,
EVENT_ID INT,
CAT_NAME_ID INT,
FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID) ON DELETE CASCADE,
FOREIGN KEY (CAT_NAME_ID) REFERENCES CAT_NAME(NAME_ID) ON DELETE CASCADE,
PRIMARY KEY (CATEGORY_ID)
);

ALTER TABLE CATEGORY AUTO_INCREMENT = 4000;

CREATE TABLE SEARCH_DATES (
SEARCH_DATE_ID INT NOT NULL AUTO_INCREMENT,
SEARCH_START DATE,
SEARCH_END DATE,
PRIMARY KEY(SEARCH_DATE_ID)
);

ALTER TABLE SEARCH_DATES auto_increment=1000;

CREATE TABLE SEARCHES(
SEARCH_ID INT NOT NULL AUTO_INCREMENT,
KEYWORD TEXT,
SEARCH_DATE_ID INT,
EVENT_ID INT,
FOREIGN KEY (SEARCH_DATE_ID) REFERENCES SEARCH_DATES(SEARCH_DATE_ID) ON DELETE CASCADE,
FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID) ON DELETE CASCADE,
PRIMARY KEY (SEARCH_ID)
);

ALTER TABLE SEARCHES AUTO_INCREMENT = 2000;

CREATE TABLE USERS (
AUTHOR_ID VARCHAR(50) NOT NULL,
CREATED_AT DATE,
LOCATION TEXT,
DESCRIPTION TEXT,
FOLLOWERS_COUNT INT,
FOLLOWING_COUNT INT,
LISTED_COUNT INT,
TWEET_COUNT INT,
VERIFIED TEXT,
PRIMARY KEY(AUTHOR_ID)
);

CREATE TABLE TWEET_TEXT (
TWEET_ID VARCHAR(50) NOT NULL,
TWEET TEXT,
PRIMARY KEY (TWEET_ID)
);

CREATE TABLE TWEET_DATA (
DATA_ID INT NOT NULL AUTO_INCREMENT,
AUTHOR_ID VARCHAR(50),
CREATED_AT DATE,
TWEET_ID VARCHAR(50),
SEARCH_ID INT,
FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(AUTHOR_ID) ON DELETE CASCADE,
FOREIGN KEY (TWEET_ID) REFERENCES TWEET_TEXT(TWEET_ID) ON DELETE CASCADE,
FOREIGN KEY (SEARCH_ID) REFERENCES SEARCHES(SEARCH_ID) ON DELETE CASCADE,
PRIMARY KEY (DATA_ID)
);

ALTER TABLE TWEET_DATA AUTO_INCREMENT = 5000;

CREATE TABLE REGIONS (
REG_ID INT NOT NULL AUTO_INCREMENT,
REGION TEXT,
PRIMARY KEY(REG_ID)
);

INSERT INTO REGIONS (REGION)
VALUES ('NORTHEAST'),
('MIDWEST'),
('WEST'),
('SOUTH');

CREATE TABLE DIVISIONS (
DIV_ID INT NOT NULL AUTO_INCREMENT,
DIVISION TEXT,
REG_ID INT,
FOREIGN KEY(REG_ID) REFERENCES REGIONS(REG_ID) ON DELETE CASCADE,
PRIMARY KEY(DIV_ID)
);

INSERT INTO DIVISIONS (DIVISION, REG_ID)
VALUES ('NEW ENGLAND', (SELECT REG_ID FROM REGIONS WHERE REGION = 'NORTHEAST')),
('MIDDLE ATLANTIC', (SELECT REG_ID FROM REGIONS WHERE REGION = 'NORTHEAST')),
('EAST NORTH CENTRAL', (SELECT REG_ID FROM REGIONS WHERE REGION = 'MIDWEST')),
('WEST NORTH CENTRAL', (SELECT REG_ID FROM REGIONS WHERE REGION = 'MIDWEST')),
('MOUNTAIN', (SELECT REG_ID FROM REGIONS WHERE REGION = 'WEST')),
('PACIFIC', (SELECT REG_ID FROM REGIONS WHERE REGION = 'WEST')),
('SOUTH ATLANTIC', (SELECT REG_ID FROM REGIONS WHERE REGION = 'SOUTH')),
('EAST SOUTH CENTRAL', (SELECT REG_ID FROM REGIONS WHERE REGION = 'SOUTH')),
('WEST SOUTH CENTRAL', (SELECT REG_ID FROM REGIONS WHERE REGION = 'SOUTH'));

CREATE TABLE US_STATES (
STATE_ID INT NOT NULL AUTO_INCREMENT,
STATE TEXT,
STATE_ABBR TEXT,
DIV_ID INT,
FOREIGN KEY(DIV_ID) REFERENCES DIVISIONS(DIV_ID) ON DELETE CASCADE,
PRIMARY KEY(STATE_ID)
);

INSERT INTO US_STATES (STATE_ABBR,STATE,DIV_ID)
VALUES ('AL','ALABAMA', (SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST SOUTH CENTRAL')),
('AK','ALASKA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'PACIFIC')),
('AZ','ARIZONA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('AR','ARKANSAS',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST SOUTH CENTRAL')),
('CA','CALIFORNIA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'PACIFIC')),
('CO','COLORADO',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('CT','CONNECTICUT',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'NEW ENGLAND')),
('DE','DELAWARE',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('FL','FLORIDA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('GA','GEORGIA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('HI','HAWAII',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'PACIFIC')),
('ID','IDAHO',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('IL','ILLINOIS',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST NORTH CENTRAL')),
('IN','INDIANA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST NORTH CENTRAL')),
('IA','IOWA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('KS','KANSAS',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('KY','KENTUCKY',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST SOUTH CENTRAL')),
('LA','LOUISIANA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST SOUTH CENTRAL')),
('ME','MAINE',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'NEW ENGLAND')),
('MD','MARYLAND',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('MA','MASSACHUSETTS',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'NEW ENGLAND')),
('MI','MICHIGAN',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST NORTH CENTRAL')),
('MN','MINNESOTA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('MS','MISSISSIPPI',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST SOUTH CENTRAL')),
('MO','MISSOURI',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('MT','MONTANA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('NE','NEBRASKA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('NV','NEVADA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('NH','NEW HAMPSHIRE',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'NEW ENGLAND')),
('NJ','NEW JERSEY',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MIDDLE ATLANTIC')),
('NM','NEW MEXICO',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('NY','NEW YORK',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MIDDLE ATLANTIC')),
('NC','NORTH CAROLINA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('ND','NORTH DAKOTA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('OH','OHIO',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST NORTH CENTRAL')),
('OK','OKLAHOMA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST SOUTH CENTRAL')),
('OR','OREGON',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'PACIFIC')),
('PA','PENNSYLVANIA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MIDDLE ATLANTIC')),
('RI','RHODE ISLAND',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'NEW ENGLAND')),
('SC','SOUTH CAROLINA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('SD','SOUTH DAKOTA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('TN','TENNESSEE',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST SOUTH CENTRAL')),
('TX','TEXAS',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST SOUTH CENTRAL')),
('UT','UTAH',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('VT','VERMONT',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'NEW ENGLAND')),
('VA','VIRGINIA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('WA','WASHINGTON',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'PACIFIC')),
('WV','WEST VIRGINIA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('WI','WISCONSIN',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST NORTH CENTRAL')),
('WY','WYOMING',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN'));

CREATE TABLE AUTHOR_LOCATION(
AUTHOR_ID VARCHAR(50),
STATE_ID INT,
FOREIGN KEY (AUTHOR_ID) REFERENCES TWEET_DATA(AUTHOR_ID) ON DELETE CASCADE,
FOREIGN KEY (STATE_ID) REFERENCES US_STATES(STATE_ID) ON DELETE CASCADE,
PRIMARY KEY(AUTHOR_ID)
);