CREATE TABLE RUN_LOG (
ID INT NOT NULL AUTO_INCREMENT,
SCRIPT TEXT,
ANCHOR_CITY_ID INT,
RUN_TIME DATETIME,
RECORDS_INSERTED INT,
RECORDS_SKIPPED INT,
PRIMARY KEY(ID)
);

CREATE TABLE EVENTS (
EVENT_ID INT NOT NULL AUTO_INCREMENT,
EVENT_NAME TEXT,
PRIMARY KEY(EVENT_ID)
);

ALTER TABLE EVENTS AUTO_INCREMENT = 3000;

CREATE TABLE CAT_NAME (
NAME_ID INT NOT NULL AUTO_INCREMENT,
NAME_TEXT TEXT,
PRIMARY KEY (NAME_ID)
);

ALTER TABLE CAT_NAME AUTO_INCREMENT = 7000;

CREATE TABLE CATEGORY(
CATEGORY_ID INT NOT NULL AUTO_INCREMENT,
EVENT_ID INT,
CAT_NAME_ID INT,
FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID) ON DELETE CASCADE,
FOREIGN KEY (CAT_NAME_ID) REFERENCES CAT_NAME(NAME_ID) ON DELETE CASCADE,
PRIMARY KEY (CATEGORY_ID)
);

ALTER TABLE CATEGORY AUTO_INCREMENT = 4000;

CREATE TABLE SEARCH_DATES (
SEARCH_DATE_ID INT NOT NULL AUTO_INCREMENT,
SEARCH_START DATE,
SEARCH_END DATE,
PRIMARY KEY(SEARCH_DATE_ID)
);

ALTER TABLE SEARCH_DATES auto_increment=1000;

CREATE TABLE SEARCHES(
SEARCH_ID INT NOT NULL AUTO_INCREMENT,
KEYWORD TEXT,
SEARCH_DATE_ID INT,
EVENT_ID INT,
FOREIGN KEY (SEARCH_DATE_ID) REFERENCES SEARCH_DATES(SEARCH_DATE_ID) ON DELETE CASCADE,
FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID) ON DELETE CASCADE,
PRIMARY KEY (SEARCH_ID)
);

ALTER TABLE SEARCHES AUTO_INCREMENT = 2000;

CREATE TABLE USERS (
AUTHOR_ID VARCHAR(50) NOT NULL,
CREATED_AT DATE,
LOCATION TEXT,
DESCRIPTION TEXT,
FOLLOWERS_COUNT INT,
FOLLOWING_COUNT INT,
LISTED_COUNT INT,
TWEET_COUNT INT,
VERIFIED TEXT,
PRIMARY KEY(AUTHOR_ID)
);

CREATE TABLE TWEET_TEXT (
TWEET_ID VARCHAR(50) NOT NULL,
TWEET TEXT,
PRIMARY KEY (TWEET_ID)
);

CREATE TABLE TWEET_DATA (
DATA_ID INT NOT NULL AUTO_INCREMENT,
AUTHOR_ID VARCHAR(50),
CREATED_AT DATE,
TWEET_ID VARCHAR(50),
SEARCH_ID INT,
FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(AUTHOR_ID) ON DELETE CASCADE,
FOREIGN KEY (TWEET_ID) REFERENCES TWEET_TEXT(TWEET_ID) ON DELETE CASCADE,
FOREIGN KEY (SEARCH_ID) REFERENCES SEARCHES(SEARCH_ID) ON DELETE CASCADE,
PRIMARY KEY (DATA_ID)
);

ALTER TABLE TWEET_DATA AUTO_INCREMENT = 5000;

CREATE TABLE AUTHOR_LOCATION(
AUTHOR_ID VARCHAR(50),
STATE_ID INT,
FOREIGN KEY (AUTHOR_ID) REFERENCES TWEET_DATA(AUTHOR_ID) ON DELETE CASCADE,
FOREIGN KEY (STATE_ID) REFERENCES US_STATES(STATE_ID) ON DELETE CASCADE,
PRIMARY KEY(AUTHOR_ID)
);